# Generated by Django 5.2.16 on 2026-07-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        ('processes', '0004_remove_process_parcel_process_land_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandParcel',
        ),
    ]
