# Generated by Django 5.2.16 on 2026-07-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_spouse_details_and_required_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='spouse_pid',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
