# Generated by Django 5.2.16 on 2026-08-02 06:57

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0004_client_spouse_pid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pid'], name='ix_client_pid_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
