# Generated by Django 5.2.16 on 2026-07-23 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0002_processinstituteentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('document_type', models.CharField(max_length=60)),
                ('input_source', models.CharField(choices=[('scanned', 'Scanned'), ('imported', 'Imported'), ('system_generated', 'System generated')], max_length=20)),
                ('ocr_status', models.CharField(choices=[('na', 'N/A'), ('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='na', max_length=12)),
                ('verification_status', models.CharField(choices=[('na', 'N/A'), ('pending', 'Pending'), ('verified', 'Verified')], default='na', max_length=12)),
                ('file_path', models.CharField(max_length=300)),
                ('display_filename', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institute_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='processes.processinstituteentry')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='processes.process')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'document',
                'indexes': [models.Index(condition=models.Q(('is_deleted', False)), fields=['process', 'step_number'], name='ix_doc_process_step')],
            },
        ),
    ]
