# Generated by Django 5.2.16 on 2026-07-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documenttemplate_generationjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('eligibility_single', 'Eligibility letter (one beneficiary)'), ('process_list', 'Beneficiary list letter'), ('case_summary', 'Compiled case summary (Step 5)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='kind',
            field=models.CharField(choices=[('eligibility', 'Eligibility letter'), ('process_list', 'Beneficiary list'), ('compiled_case', 'Compiled case export')], max_length=20),
        ),
    ]
