# Generated by Django 5.2.16 on 2026-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_refile_under_pid_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('eligibility_single', 'Eligibility letter (one beneficiary)'), ('process_list', 'Beneficiary list letter'), ('case_summary', 'Compiled case summary (Step 5)'), ('process_codes', 'Beneficiary code list')], max_length=32),
        ),
        migrations.AlterField(
            model_name='generationjob',
            name='kind',
            field=models.CharField(choices=[('eligibility', 'Eligibility letter'), ('process_list', 'Beneficiary list'), ('compiled_case', 'Compiled case export'), ('process_codes', 'Beneficiary code list')], max_length=20),
        ),
    ]
