# Generated by Django 5.2.16 on 2026-08-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_readable_case_filenames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('eligibility_single', 'Eligibility letter (one beneficiary)'), ('process_list', 'Beneficiary list letter'), ('case_summary', 'Compiled case summary (Step 5)'), ('process_codes', 'Beneficiary code list'), ('request_form', 'Request form (blank, for printing)')], max_length=32),
        ),
    ]
