# Generated by Django 5.2.16 on 2026-07-22 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('verify', 'Verify'), ('override', 'Override'), ('generate', 'Generate'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='activity_lo_entity__2a2d99_idx'), models.Index(fields=['actor', '-created_at'], name='activity_lo_actor_i_bd2550_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_61fa17_idx')],
            },
        ),
    ]
