# Generated by Django 5.2.16 on 2026-08-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='app_build',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
