# Generated by Django 5.2.16 on 2026-07-22 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('overall_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('rejected', 'Rejected')], default='draft', max_length=12)),
                ('current_step', models.PositiveSmallIntegerField(default=1)),
                ('lawyer_notes', models.TextField(blank=True)),
                ('duplicate_flagged', models.BooleanField(default=False)),
                ('assigned_lawyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_processes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='catalog.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='clients.client')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='parcels.landparcel')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='DuplicateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('match_reason', models.CharField(choices=[('pid', 'PID exact match'), ('mother_name', 'Mother-name fuzzy match')], max_length=20)),
                ('reason', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_overrides', to='clients.client')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('overridden_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duplicate_overrides', to='processes.process')),
            ],
            options={
                'db_table': 'duplicate_override',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('missing', 'Missing files'), ('complete', 'Complete')], default='not_started', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10)),
                ('out_of_city_flag', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='processes.process')),
            ],
            options={
                'db_table': 'process_step',
            },
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['created_at'], name='ix_process_created_at'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['client'], name='ix_process_client'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['category', 'overall_status', 'assigned_lawyer'], name='ix_process_filters'),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('overall_status', 'rejected'), _negated=True)), fields=('client',), name='ix_process_active_alloc'),
        ),
        migrations.AddConstraint(
            model_name='processstep',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('process', 'step_number'), name='ix_step_process_number_active'),
        ),
    ]
