# Generated by Django 5.2.16 on 2026-07-23 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_processinstituteentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='processinstituteentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_custom', False), ('is_deleted', False), models.Q(('institute_code', ''), _negated=True)), fields=('process', 'step_number', 'institute_code'), name='ix_entry_fixed_unique'),
        ),
    ]
