# Generated by Django 5.2.16 on 2026-07-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_processinstituteentry_ix_entry_fixed_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='parcel',
        ),
        migrations.AddField(
            model_name='process',
            name='land_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='process',
            name='land_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
