# Generated by Django 5.2.16 on 2026-07-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_remove_process_parcel_process_land_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='similar_name_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
