# Generated by Django 5.2.16 on 2026-08-05 06:27

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0005_client_ix_client_pid_trgm'),
        ('processes', '0010_add_completed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='process',
            index=django.contrib.postgres.indexes.GinIndex(fields=['unique_code'], name='ix_process_code_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
