# Generated by Django 5.2.16 on 2026-08-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0014_land_id_search_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='fast_entry',
            field=models.BooleanField(default=False),
        ),
    ]
