# Generated by Django 5.2.16 on 2026-07-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0003_alter_documenttemplate_template_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=300)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='documents.document')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_scan',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['uploaded_by', '-created_at'], name='ix_scan_uploader'), models.Index(condition=models.Q(('confirmed_at__isnull', True)), fields=['-created_at'], name='ix_scan_unconfirmed')],
            },
        ),
    ]
